# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eoM32V02QBQ7whSGA5Tyk8d15NanA5ox
"""

!pip install streamlit
import streamlit as st
import pandas as pd

st.title("Employee Attrition Dashboard")

df = pd.read_excel("Palo Alto Networks.xlsx")

st.write(df)